db.user.insertMany([
    {'_id': 'gojo_satoru',
     'Name': 'Satoru',
     'Surname': 'Gojo',
     'BirthDate': '1989-12-7',
     'Password': 'gojo_satoru',
     'Type': '0'},
    {'_id': 'sung_jinwoo',
     'Name': 'Jinwoo',
     'Surname': 'Sung',
     'BirthDate': '2001-03-8',
     'Password': 'sung_jinwoo',
     'Type': '0'},
    {'_id': 'mustang_roy',
     'Name': 'Roy',
     'Surname': 'Mustang',
     'BirthDate': '1975-03-25',
     'Password': 'mustang_roy',
     'Type': '0'},
     {'_id': 'uchiha_itachi',
      'Name': 'Itachi',
      'Surname': 'Uchiha',
      'BirthDate': '1985-06-9',
      'Password': 'uchiha_itachi',
      'Type': '0'}
    ]);